name: black_hole
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
  shared_preferences: ^2.2.3
  flutter_screenutil: ^5.9.3
  flutter_localization: ^0.2.0
  loading_animation_widget: ^1.2.1
  intl: ^0.19.0
  dio: ^5.5.0+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NotoSans-Black.ttf
          weight: 900